apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry-app
  template:
    metadata:
      name: telemetry-pod
      labels:
        app: telemetry-app
    spec:
      containers:
        - name: telemetry
          image: acrdevproject4480.azurecr.io/axion-telemetry-query-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://admin:admin%40%23123@database-service:9090/mydatabase"