apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: dev
type: Opaque
stringData:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "admin@#123"
  POSTGRES_DB: "mydatabase"
  DATABASE_URL: "postgresql://admin:admin%40%23123@database-service:9090/mydatabase"
