apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: my-azure-secret-provider
  namespace: default

spec:
  provider: azure

  secretObjects:
    - secretName: mysecret
      type: Opaque
      data:
        - key: POSTGRES_USER
          objectName: postgres-username

        - key: POSTGRES_PASSWORD
          objectName: postgres-password

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "73959b77-371d-435b-9e19-1837a1ba9c4d"

    keyvaultName: "keyvault4480"
    tenantId: "414cc38f-596d-4a74-80a2-c5b089d38f80"

    objects: |
      array:
        - |
          objectName: postgres-username
          objectType: secret

        - |
          objectName: postgres-password
          objectType: secret